### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by KacerCZ** [contributte/codeception#11]
Issue #9 to prepare version 1.0 is already closed, but version 1.0 is still not released/tagged.
Could you please make proper release to make possible upgrade from arachne/codeception?

**Comment by f3l1x** [comment]
Done. 

https://github.com/contributte/codeception/releases/tag/v1.0.0

**Comment by enumag** [comment]
Great! I marked arachne/codeception as abandoned on packagist. Now I need to update the other arachne packages...

**Comment by KacerCZ** [comment]
Thanks.
