### ISSUE TITLE
 Double slash in appDir/wwwDir

### ISSUE THREAD

**Issue by lukascellar** [contributte/codeception#26]
Paths in `NetteDIModule` contains double slash `//` and cause problems in template path normalization used in `Latte\Loaders\FileLoader::normalizePath`

```
appDir => "/dev/my-project/tests/functional//../../app"
wwwDir => "/dev/my-project/tests/functional//../../www" 
```

Solutiion:
trim tailing slash in `_beforeSuite` method

**Comment by f3l1x** [comment]
Your PR was merged, I am closing it here.

https://github.com/contributte/codeception/pull/27
