### ISSUE TITLE
Cannot assign null to property Nette\Caching\Storages\SQLiteJournal::$pdo of type PDO when running tests

### ISSUE THREAD

**Issue by Snooker147** [contributte/codeception#37]
Hello,

after upgrading to the newest version of Nette caching library and running codeception tests I now get the following error:
`Cannot assign null to property Nette\Caching\Storages\SQLiteJournal::$pdo of type PDO` right after the tests are finished.

This looks to be an issue with the latest Nette\Caching commit [here](https://github.com/nette/caching/commit/82b622fcd101340c9419f3e9ee4452b64677b1e3#diff-743ef85dd856165203e0031faa1b003ec2585055da336039b02f75021adb74ac) which does no longer allow the `$pdo` property to be nullable.

Detailed error stacktrace: 
![image](https://user-images.githubusercontent.com/10927481/215722200-9aaec4e5-0f91-4eee-8e6d-7e95b1dc49cb.png)

I switched to a prior version without that commit (Nette\Caching v3.1.4) and the error no longer appears. Can we get this fixed please, so that we can use the newest Nette\Caching version?

Thanks!

**Comment by her-ur** [comment]
It seems that should be enough to call `$journal->clean([Cache::All => true]);` instead of setting null via reflection. What do you think?

**Comment by rattuscz** [comment]
:+1:
