### ISSUE TITLE
SCRIPT_NAME is missing FROM $_SERVER superglobal

### ISSUE THREAD

**Issue by northys** [contributte/codeception#8]
I have found little bug, when you are preparing request for nette. You reset `$_SERVER` using BrowserKit's `$request->getServer(`) but it does not contain **SCRIPT_NAME** needed by phpunit.

When uncaught exception comes to phpunit's filtering logic it falls. For example:

1. test logs [Nette\Application\ApplicationException] Too many loops detected in application life cycle. 
2. fails because we have log checking module for codeception

See https://github.com/sebastianbergmann/phpunit/blob/cdcb7376a773beac6dd0cd4b38bb5901e8534035/src/Util/Filter.php#L31. Is there any solution for this, please?

**Comment by enumag** [comment]
Well I guess we could preserve it from the old `$_SERVER`. That should solve it, right? Are there any other keys that should be preserved? Or should I rather merge `$request->getServer()` into `$_SERVER` instead of replacing it completely?

**Comment by northys** [comment]
I don't have answer for the first question. **SCRIPT_NAME** by phpstorm. I don't know about any other keys needed.

+1 for merging, can I prepare PR?

**Comment by enumag** [comment]
Sure, but please test the updated version on your application first. I'm not entirely sure if merging can break anything or not.

**Comment by enumag** [comment]
ping @northys

**Comment by northys** [comment]
@enumag sorry, I forgot to create PR. you can expect it on monday.

**Comment by mabar** [comment]
Ping @northys

**Comment by northys** [comment]
@mabar since I no longer work at uloz.to where this problem occurred and I cannot find the commit where I've fixed it I cannot create PR. If no one else has this problem you can close the issue.
